# -*- coding: utf-8 -*-
"""Streamlit Partie 3 - Fonctionnalités avancées.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOX7_V-fqK1XIafK--1_ZnAV3umIWar9
"""

import streamlit as st
from streamlit_authenticator import Authenticate
from streamlit_option_menu import option_menu

# Données des utilisateurs
lesDonneesDesComptes = {
    'usernames': {
        'utilisateur': {
            'name': 'Utilisateur',
            'password': 'utilisateurMDP',  # À hasher en production
            'email': 'utilisateur@gmail.com',
            'failed_login_attemps': 0,
            'logged_in': False,
            'role': 'utilisateur'
        },
        'root': {
            'name': 'Admin',
            'password': 'rootMDP',  # À hasher en production
            'email': 'admin@gmail.com',
            'failed_login_attemps': 0,
            'logged_in': False,
            'role': 'administrateur'
        }
    }
}

# Initialisation de l'authentificateur
authenticator = Authenticate(
    lesDonneesDesComptes,
    "cookie_name",  # Nom du cookie
    "cookie_key",  # Clé du cookie
    cookie_expiry_days=30
)

# Authentification
authenticator.login()

if st.session_state.get("authentication_status"):
    # Menu avec streamlit-option-menu
    with st.sidebar:
        authenticator.logout("Déconnexion", "sidebar")
        menu = option_menu(
            menu_title="Menu",
            options=["Accueil", "Photos"],
            icons=["house", "camera"],
            menu_icon="cast",
            default_index=0
        )

    # Pages
    if menu == "Accueil":
        st.title("Bienvenue sur ma page d'accueil")
        st.image("https://media.giphy.com/media/3o6ZtaO9BZHcOjmErm/giphy.gif", caption="Applaudissements!")
    elif menu == "Photos":
        st.title("Bienvenue dans l'album photo 🐱")
        col1, col2, col3 = st.columns(3)
        with col1:
            st.image("https://static.streamlit.io/examples/cat.jpg", caption="Chat 1")
        with col2:
            st.image("https://i-sam.unimedias.fr/2018/08/10/istock-160515715.jpg?auto=format%2Ccompress&crop=faces&cs=tinysrgb&fit=crop&h=501&w=890", caption="Chat 2")
        with col3:
            st.image("https://images.ctfassets.net/denf86kkcx7r/57uYN7JlyDtQ91KvRldrm9/0a0656983993f5e09c4daa0a4fd8f5e6/comment-punir-son-chat-91?fm=webp&w=913", caption="Chat 3")

elif st.session_state.get("authentication_status") is False:
    st.error("Nom d'utilisateur ou mot de passe incorrect.")
else:
    st.warning("Les champs username et mot de passe doivent être remplis.")

